<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Create</strong> new ldap mapping' => '',
    '<strong>Edit</strong> ldap mapping' => '',
    '<strong>LDAP</strong> member mapping' => '',
    'Assign LDAP users which becomes automatically member of this group.' => '',
    'Assign LDAP users which becomes automatically member of this space.' => '',
    'Attribute value (e.g. street==Some Street <i>or</i> street=~Street)' => '',
    'Back to overview' => '',
    'Create new mapping' => '',
    'LDAP Mapping' => '',
    'Mapping options:' => '',
    'Note: This option is only available for global user administrators.' => '',
    'Part of the users base DN (e.g. OU=People,DC=example,DC=com)' => '',
    'Space ID' => '',
    'User Memberships (MemberOf, e.g. CN=xyz_space_access,OU=Groups,DC=example,DC=com)' => '',
    'Group' => 'グループ',
    'ID' => 'ID',
    'LDAP' => 'LDAP',
];
